### ISSUE TITLE
Broken link to std-lib docs

### ISSUE THREAD

**Issue by dmihal** [FuelLabs/docs-hub#114]
The documentation links to [https://fuellabs.github.io/sway/master/std/](https://docs.fuel.network/docs/sway/std/), however this link is broken.

**Comment by calldelegation** [comment]
Hey @dmihal, where are you seeing this? The link leads to https://fuellabs.github.io/sway/master/std/. The link you provided directs to https://docs.fuel.network/docs/sway/std/, which is broken, but it's not the original link that you mentioned.

<img width="1920" alt="Screenshot 2023-11-20 at 6 17 27 PM (2)" src="https://github.com/FuelLabs/docs-hub/assets/106365423/ad3892df-8121-4d8c-bd70-4b27514b6887">

<img width="1920" alt="Screenshot 2023-11-20 at 6 19 58 PM (2)" src="https://github.com/FuelLabs/docs-hub/assets/106365423/1a6c7b70-43aa-4c07-90b3-4cea846a60e0">
