### ISSUE TITLE
docs: Running a node requirements 

### ISSUE THREAD

**Issue by calldelegation** [FuelLabs/docs-hub#117]
In all the 'running a node' guides, the minimum requirements are missing. For example, they should include 8 GB of RAM and at least 1 TB of free disk space.

**Comment by Voxelot** [comment]
This largely depends on the volume of RPC traffic, but here are some general guidelines for beta-4

|         | Minimum | Recommended |
|---------|---------|-------------|
| CPU     | 2 Cores | 8 Cores     |
| Memory  | 4 GB    | 12 GB       |
| Storage | 30 GB   | 100 GB      |
