### ISSUE TITLE
docs: replace curl link

### ISSUE THREAD

**Issue by calldelegation** [FuelLabs/docs-hub#125]
curl -sSf https://install.fuel.network/fuelup-init.sh | sh" 

--proto '=https' --tlsv1.2 can be removed right away as suggested by @cold-briu

**Comment by cold-briu** [comment]
Just FYI: this idea comes from a discussion in slack. The final goal is something like this: 

_Now:
curl --proto '=https' --tlsv1.2 -sSf \ https://install.fuel.network/fuelup-init.sh | sh

Ideal:
curl -sSf https://fuel.network/install | sh_
