### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Mk-turner** [FuelLabs/docs-hub#177]
### What version of fuels-ts are you using?

https://www.fuel.network/

### Steps to Reproduce

https://docs.fuel.network/docs/indexer/. this we need the indexer

### Expected Behavior

there should be an indexer on the page this should make it to work perfectly fine.

### Actual Behavior

https://docs.fuel.network/docs/indexer/.  error page turning up

**Comment by arboleya** [comment]
cc @sarahschwartz

**Comment by arboleya** [comment]
@Mk-turner We removed these docs because the `indexer` got deprecated.

However, you can still find the docs in the repo and run `mdbook` locally:

 - https://github.com/FuelLabs/fuel-indexer
