### ISSUE TITLE
Glossary: Remove `indexer` related items

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/docs-hub#178]
I think we still have something lingering in the glossary.

The resulting link below points to this [broken] page:
 - https://docs.fuel.network/docs/intro/glossary/#indexer

![search](https://github.com/FuelLabs/docs-hub/assets/26660/0a9ffce7-c726-42aa-a618-f8fd5b796698)

**Comment by sarahschwartz** [comment]
We will add some docs about indexer options soon, so I think it makes sense to keep the definition in the glossary for now.
