### ISSUE TITLE
Contract Deployment Wallet Error

### ISSUE THREAD

**Issue by harrisonjoseph17** [FuelLabs/docs-hub#193]
Had issues after importing my wallet during contract deployment code. Forc command couldnt detect the imported wallet. 

![image](https://github.com/FuelLabs/docs-hub/assets/26278790/161d6655-46d8-4677-a93e-c0958e9205cf)

**Comment by sarahschwartz** [comment]
Hi @harrisonjoseph17 , can you elaborate on the steps you took to get this error?
