### ISSUE TITLE
TypeScript imports are not being rendered

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/docs-hub#233]
Related to issue: https://github.com/FuelLabs/fuels-ts/issues/1960

## Summary

TypeScript code snippets have import statements, which aren't being rendered correctly (examples below).
- [Docs Hub](https://docs.fuel.network/docs/nightly/fuels-ts/cookbook/custom-transactions-from-contract-calls/)
`// #import { bn, Contract, FunctionInvocationResult };`
- [Fuels-ts Docs](https://fuellabs.github.io/fuels-ts/guide/cookbook/custom-transactions-from-contract-calls.html)
`import { FunctionInvocationResult, Contract, bn } from 'fuels';`

The `fuels-ts` docs has a custom [plugin](https://github.com/FuelLabs/fuels-ts/blob/master/apps/docs/.vitepress/plugins/snippetPlugin.ts#L148-L162) which renders our code snippet imports. 

I believe there is work to be done on both repositories, so it would be good to align on this.

### Expected

Code snippet imports to be rendered correctly.

e.g. `import { FunctionInvocationResult, Contract, bn } from 'fuels';`

### Actual

Code snippet imports are not rendered.

e.g. `// #import { bn, Contract, FunctionInvocationResult };`

**Comment by sarahschwartz** [comment]
I believe I can make this fix on the docs-hub side without any changes in the `fuels-ts` repo, thanks!
