### ISSUE TITLE
Docs: Problems with reading docs in certain environments

### ISSUE THREAD

**Issue by osrm** [FuelLabs/docs-hub#399]
https://github.com/FuelLabs/docs-hub/pull/393

              > Links works without .mdx extension

May I ask your os environment? Mine is windows 10 / chrome. Links are not working without extension in my environment. @calldelegation

And I also tried brave / firefox / opera / edge and mobile environment(iPhone's safari browser), but those don't work either.

![fuel extension](https://github.com/user-attachments/assets/7e63792b-997b-4e2c-bd7b-9e646592dcf3)

_Originally posted by @osrm in https://github.com/FuelLabs/docs-hub/issues/393#issuecomment-2307479326_

---------------------------------------

As discussed above, I was having issues with certain links in certain articles not working correctly on my operating system (Microsoft Windows 10 / Chrome, Opera, Brave, Firefox, Edge Browser and Apple iPhone 15 / Safari Browser) and wanted to fix it. I thought it was mostly due to the missing ‘extension’, so I fixed it and confirmed that it worked correctly in my environment.

However, PR's comments were existing documentation was working fine and there was no need to modify it.

And I also have checked in both Wifi and 4G-LTE environments and the links before the fix were non-functional and after the extension was fixed, the links all worked fine.

Can I get someone to check if this is the case in other environments and help me resolve this?

The modified links can be found here.: 

https://github.com/FuelLabs/docs-hub/pull/393/files

**Comment by alfiedotwtf** [comment]
The .mdx files in the repository are just the source files used to generate the resulting HTML e.g take a look at:

https://raw.githubusercontent.com/FuelLabs/docs-hub/master/docs/contributing/style-guide.mdx

This file after rendering gets turned into the final page:

https://docs.fuel.network/docs/contributing/style-guide/

**Comment by osrm** [comment]
I totally understand, thank you for your kind reply.

**Comment by osrm** [comment]
I understand. Thank you
